#Jinja2's conditional statements allow you to specify conditions for evaluating and rendering different parts of a template. The when statement is used to conditionally include or exclude a block of code in a template based on the value of a variable.

#Here's an example of using the when statement in an Ansible playbook:

---
- name: Use Jinja2 conditional statement: when in Ansible
  hosts: all
  become: yes
  gather_facts: no
  vars:
    message: "Hello, {{ username }}!"
    username: "User"

  tasks:
  - name: Create a file with Jinja2 conditional statement
    copy:
      content: |
        {% if username == "User" %}
        {{ message }}
        {% else %}
        {{ username }}
        {% endif %}
      dest: /tmp/message.txt

#In this playbook, the copy module is used to create a file at /tmp/message.txt with the content of a Jinja2 template. The template contains a when statement that checks the value of the username variable.

#If the username is equal to "User", the template will render Hello, User!. Otherwise, it will render the value of username.

#Note: You can use the when statement along with other Jinja2 features, such as loops and filters, to create complex and dynamic templates in Ansible.
