#Here are some examples of Ansible playbooks you can use to manage services on a Linux server:

#1. Start a Service:

---
- name: Start a Service
  hosts: all
  tasks:
    - name: Start the Apache service
      service:
        name: apache2
        state: started

#2. Stop a Service:

---
- name: Stop a Service
  hosts: all
  tasks:
    - name: Stop the Apache service
      service:
        name: apache2
        state: stopped

#3. Restart a Service:

---
- name: Restart a Service
  hosts: all
  tasks:
    - name: Restart the Apache service
      service:
        name: apache2
        state: restarted

#4. Reload a Service:

---
- name: Reload a Service
  hosts: all
  tasks:
    - name: Reload the Apache service
      service:
        name: apache2
        state: reloaded

#Note: In these examples, the service being managed is Apache, and the name of the service on a Linux system is typically apache2. The name of the service may be different on different Linux distributions, so make sure to check the name of the service on your system before running these playbooks.
